export const entitiesConfig = {
  items: {
    label: "Items",
    subtitle: "Manage magical items and artifacts",
    api: "/api/items",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "type", label: "Type", type: "text" },
      { name: "rarity", label: "Rarity", type: "text" },
      { name: "image", label: "Image", type: "file" },
    ],
    imageField: "image_url",
    descriptionField: "rarity",
  },
  npcs: {
    label: "NPCs",
    subtitle: "Your cast of characters across all campaigns",
    api: "/api/npcs",
    preview: {
      enabled: true,
      fields: [
        { name: "name", label: "Name" },
        { name: "race", label: "Race" },
        { name: "class", label: "Class" },
        { name: "alignment", label: "Alignment" },
        { name: "age", label: "Age" },
        { name: "hair_color", label: "Hair" },
        { name: "eye_color", label: "Eyes" },
        { name: "skin_color", label: "Skin" },
        { name: "height", label: "Height" },
        { name: "weight", label: "Weight" },
        { name: "personality_traits", label: "Personality" },
        { name: "ideals", label: "Ideals" },
        { name: "bonds", label: "Bonds" },
        { name: "flaws", label: "Flaws" },
        { name: "backstory", label: "Backstory" },
        { name: "location_name", label: "Location Name", type: "select-location" }
      ]
    },
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "race", label: "Race", type: "text", layout: { width: "half" } },
      { name: "class", label: "Class", type: "text", layout: { width: "half" } },
      { name: "alignment", label: "Alignment", type: "text", layout: { width: "half" } },
      { name: "age", label: "Age", type: "text", layout: { width: "half" } },
      { name: "hair_color", label: "Hair Color", type: "text", layout: { width: "third" } },
      { name: "eye_color", label: "Eye Color", type: "text", layout: { width: "third" } },
      { name: "skin_color", label: "Skin Color", type: "text", layout: { width: "third" } },
      { name: "height", label: "Height", type: "text", layout: { width: "half" } },
      { name: "weight", label: "Weight", type: "text", layout: { width: "half" } },
      { name: "personality_traits", label: "Personality Traits", type: "longtext", layout: { width: "full", rows: 3 } },
      { name: "ideals", label: "Ideals", type: "longtext", layout: { width: "full", rows: 3 } },
      { name: "bonds", label: "Bonds", type: "longtext", layout: { width: "full", rows: 3 } },
      { name: "flaws", label: "Flaws", type: "longtext", layout: { width: "full", rows: 3 } },
      { name: "backstory", label: "Backstory", type: "longtext", layout: { width: "full", rows: 6 } },
      { name: "location_name", label: "Location Name", type: "select-location", layout: { width: "full" } },
      { name: "image", label: "Image", type: "file" },
    ],
    imageField: "image_url",
    descriptionField: "race",
  },
  notes: {
    label: "Notes",
    subtitle: "Capture ideas, lore, and everything in between",
    api: "/api/notes",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "content", label: "Content", type: "longtext", layout: { width: "full", rows: 6 } },
    ],
    imageField: undefined,
    descriptionField: "content",
  },
  locations: {
    label: "Locations",
    subtitle: "Track every city, cave, and lair your players visit",
    api: "/api/locations",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "type", label: "Type", type: "text" },
      { name: "description", label: "Description", type: "text" },
      { name: "map", label: "Map", type: "file" },
      { name: "sequential_next_location_ids", label: "Sequential Next Locations", type: "hidden" }
    ],
    imageField: "map_url",
    descriptionField: "type",
  },
  encounters: {
    label: "Encounters",
    subtitle: "Plan battles, challenges, and enemy groups",
    api: "/api/encounters",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "campaign_location_id", label: "Location", type: "select-location" },
      { name: "difficulty", label: "Difficulty", type: "text" },
      { name: "creatures", label: "Number of Creatures", type: "text" },
      { 
        name: "npc_ids", 
        label: "NPCs in Encounter", 
        type: "multiselect-npc", 
        required: false 
      },
      { name: "notes", label: "Notes", type: "text" },
    ],
    imageField: undefined,
    descriptionField: "difficulty",
  },
  sessions: {
    label: "Sessions",
    subtitle: "Schedule and review your campaign's sessions",
    api: "/api/sessions",
    fields: [
      { name: "date", label: "Date", type: "date" },
      { name: "time", label: "Time", type: "time" },
      { name: "location", label: "Location", type: "text" },
      { name: "notes", label: "Notes", type: "text" },
    ],
    imageField: undefined,
    descriptionField: "date",
  },
  campaigns: {
    label: "Campaigns",
    subtitle: "Manage your epic adventures and quests",
    api: "/api/campaigns",
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "description", label: "Description", type: "text" },
      { name: "image", label: "Image", type: "file" },
    ],
    imageField: "image_url",
    descriptionField: "description",
  },
  // Add more entities here (campaigns, etc.)
}; 